### ISSUE TITLE
Not work with win7 platform

### ISSUE THREAD

**Issue by dqmmpb** [boneskull/gulp-jekyll-stream#10]
Under linux platform, it works fine!
But, when I use cygwin+ruby in win7 platform, it throw error
<code>
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
</code>

I think maybe the command not find jekyll. So I change the lib/index.js
<code>
    done(null, (options.bundleExec ? ['bundle', 'exec'] : [])
      .concat([process.platform === 'win32' ? 'jekyll.bat' : 'jekyll', 'build'])
      .concat(dargs(options, {
        includes: includes
      })), options);
</code>
it works.
I want to know why? Is it the error of ruby? or jekyll? or others?

**Comment by boneskull** [comment]
yeah, don't know.  maybe I need cross-spawn in here.
